name: Clone

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL'
        required: true
        type: string
        default: 'https://github.com'
      release_tag:
        description: 'Release Tag'
        required: true
        type: string
        default: 'v1.0.0'

jobs:
  get-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: fetch specific url/tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RAW_URL: ${{ inputs.url }}
          TAG: ${{ inputs.release_tag }}
        run: |
          CLEANED_REPO=$(echo "$RAW_URL" | sed 's|/$||' | awk -F'/' '{print $(NF-1)"/"$NF}')
          
          if ! gh release download "$TAG" --repo "$CLEANED_REPO" --archive=zip --output release.zip 2>/dev/null; then
            curl -L "https://github.com{CLEANED_REPO}/archive/refs/tags/${TAG}.zip" -o release.zip
          fi

      - name: create the nested folder
        run: |
          mkdir -p src/vendor/release-data

      - name: extract
        run: |
          unzip release.zip \
            -d src/vendor/release-data/

      - name: commit
        env:
          ACTOR_NAME: ${{ github.actor }}
          ACTOR_ID: ${{ github.actor_id }}
          REPO_URL: ${{ inputs.url }}
          TAG: ${{ inputs.release_tag }}
        run: |
          AUTO_EMAIL="${ACTOR_ID}+${ACTOR_NAME}@users.noreply.github.com"
          git config user.name "$ACTOR_NAME"
          git config user.email "$AUTO_EMAIL"
          git add .
          git commit -m "Add release $TAG from $REPO_URL" \
                     -m "Co-authored-by: github-actions <github-actions@github.com>"
          git push
          
